name: pollution_modelling
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - anaconda=custom=py37_0
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1
  - cryptography=2.6.1=py37ha12b0ac_0
  - et_xmlfile=1.0.1=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - hdf5=1.10.4=hfa1e0ec_0
  - idna=2.8=py37_0
  - intel-openmp=2019.1=144
  - jdcal=1.4.1=py_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.36=ha441bb4_0
  - libprotobuf=3.6.1=hd9629dc_0
  - mkl=2019.1=144
  - ncurses=6.1=h0a44026_1
  - openpyxl=2.6.2=py_0
  - openssl=1.1.1b=h1de35cc_1
  - pip=19.1.1=py37_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.0=py37_0
  - python=3.7.2=haf84260_0
  - readline=7.0=h1de35cc_5
  - requests=2.21.0=py37_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - cycler==0.10.0
    - gast==0.2.2
    - geographiclib==1.49
    - geopy==1.19.0
    - grpcio==1.20.1
    - h5py==2.9.0
    - joblib==0.13.2
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - kiwisolver==1.1.0
    - markdown==3.1
    - matplotlib==3.1.0
    - mock==3.0.5
    - numpy==1.16.3
    - protobuf==3.7.1
    - pymongo==3.8.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - scikit-learn==0.21.1
    - scipy==1.2.1
    - six==1.12.0
    - sklearn==0.0
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - utm==0.4.2
    - werkzeug==0.15.4

